### ISSUE TITLE
System JS error

### ISSUE THREAD

**Issue by StefBrierre** [techiediaries/ngx-qrcode#1]
Hello. 
I'm trying to add you library to my Angular 4 project, 
unfortunatly I have the following error : 
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ngx-qrcode2
Error: XHR error (404 Not Found) loading http://localhost:3000/ngx-qrcode2
at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1032:39)
at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:414:31)
at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:181:47)
at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:476:38)
Error loading http://localhost:3000/ngx-qrcode2 as "ngx-qrcode2" from http://localhost:3000/app/app.module.js
at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1032:39)
at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:414:31)
at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:181:47)
at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:476:38)
Error loading http://localhost:3000/ngx-qrcode2 as "ngx-qrcode2" from http://localhost:3000/app/app.module.js

I've followed the processed you described above and I'm based my app on Angular 4 quickstart.

Is there something that I've missed ?

**Comment by techiediaries** [comment]
Just use Webpack instead of SystemJS, you can use the Angular CLI  which will generate an Angular project based on Webpack.
