### ISSUE TITLE
Angular Universal - Prerendering failed

### ISSUE THREAD

**Issue by empystudio** [techiediaries/ngx-qrcode#38]
Hi,
I installed the module in my project (Angular 7.2.13) and it's working fine.
When I try to use it with the Angular Univeral I get this error

```
Prerendering failed because of error: 
..\node_modules\ngx-qrcode2\index.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, Input, NgModule, Renderer2, ViewChild } from '@angular/core';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

I hope this can be fixed

**Comment by rafa-as** [comment]
Can you check the new version 9, please?

**Comment by rafa-as** [comment]
Closed due inactivity
